export const dummyMenus = [
  {
    title: '강의',
    items: [
      {
        title: '개발 · 프로그래밍',
        items: [
          {
            title: '웹 개발',
            items: [
              { title: 'HTML/CSS' },
              { title: 'JavaScript' },
              { title: 'React' },
              { title: 'Node.js' },
              { title: 'Java' },
              { title: 'Spring' },
              { title: 'Vue.js' },
              { title: 'Python' },
              { title: '웹앱' },
              { title: 'Django' },
              { title: 'jQeury' },
              { title: 'Spring Boot' },
            ],
          },
          {
            title: '프론트엔드',
            items: [
              { title: 'HTML/CSS' },
              { title: 'JavaScript' },
              { title: 'React' },
              { title: 'Java' },
              { title: 'Node.js' },
              { title: 'Spring' },
              { title: 'Vue.js' },
              { title: 'Python' },
              { title: '웹앱' },
              { title: 'Django' },
              { title: 'jQeury' },
              { title: 'Spring Boot' },
            ],
          },
          {
            title: '백엔드',
            items: [
              { title: 'Spring' },
              { title: 'Java' },
              { title: 'Spring Boot' },
              { title: 'Node.js' },
              { title: 'JPA' },
              { title: 'AWS' },
              { title: 'Docker' },
              { title: 'MVC' },
              { title: 'REST API' },
              { title: 'Express' },
              { title: 'Kubernetes' },
              { title: 'Python' },
            ],
          },
          {
            title: '풀스택',
            items: [
              { title: 'React' },
              { title: 'Django' },
              { title: 'Node.js' },
              { title: 'MongoDB' },
              { title: 'Firebase' },
              { title: 'JavaScript' },
              { title: 'Python' },
              { title: 'Express' },
              { title: 'HTML/CSS' },
              { title: '클론코딩' },
              { title: 'Bootstrap' },
              { title: '웹앱' },
            ],
          },
          {
            title: '모바일 앱 개발',
            items: [
              { title: 'Android' },
              { title: 'iOS' },
              { title: 'Swift' },
              { title: 'Kotlin' },
              { title: 'Flutter' },
              { title: 'Firebase' },
              { title: 'SwiftUI' },
              { title: 'Java' },
              { title: 'React Native' },
              { title: 'IONIC' },
              { title: 'Jetpack' },
              { title: '하이브리드 앱' },
            ],
          },
          {
            title: '게임 개발',
            items: [
              { title: 'Unity' },
              { title: 'C#' },
              { title: 'Unreal Engine' },
              { title: 'iOS' },
              { title: 'C++' },
              { title: 'UE Blueprint' },
              { title: 'Swift' },
              { title: '블록코딩' },
              { title: 'Scratch' },
              { title: 'Roblox' },
              { title: '메타버스' },
              { title: 'GUI' },
            ],
          },
          {
            title: '프로그래밍 언어',
            items: [
              { title: 'Python' },
              { title: 'JavaScript' },
              { title: 'Java' },
              { title: 'C' },
              { title: 'C++' },
              { title: '코딩 테스트' },
              { title: 'Swift' },
              { title: 'ES6' },
              { title: 'C#' },
              { title: '객체지향' },
              { title: 'TypeScript' },
              { title: 'R' },
            ],
          },
          {
            title: '알고리즘 · 자료구조',
            items: [
              { title: '코딩 테스트' },
              { title: 'Python' },
              { title: 'Java' },
              { title: 'C' },
              { title: 'C++' },
              { title: '기술면접' },
              { title: 'JavaScript' },
              { title: '운영체제' },
              { title: 'C#' },
              { title: '면접' },
              { title: 'Scratch' },
              { title: '양자 컴퓨팅' },
            ],
          },
          {
            title: '데이터베이스',
            items: [
              { title: 'SQL' },
              { title: 'DBMS/RDBMS' },
              { title: '데이터 엔지니어링' },
              { title: 'MySQL' },
              { title: 'MSSQL' },
              { title: 'Oracle' },
              { title: 'PostgreSQL' },
              { title: 'MongoDB' },
              { title: 'MariaDB' },
              { title: 'Python' },
              { title: 'Notion' },
              { title: 'Java' },
            ],
          },
          {
            title: '데브옵스 · 인프라',
            items: [
              { title: 'AWS' },
              { title: 'Docker' },
              { title: 'Linux' },
              { title: '네트워크' },
              { title: 'Kubernetes' },
              { title: 'Azure' },
              { title: 'Google Cloud Platform' },
              { title: '서버리스' },
              { title: 'Ansible' },
              { title: 'CI/CD' },
              { title: '데이터 엔지니어링' },
              { title: 'Shell Script' },
            ],
          },
          {
            title: '임베디드 · IoT',
            items: [
              { title: 'Arduino' },
              { title: 'IoT' },
              { title: '임베디드' },
              { title: 'FPGA' },
              { title: 'Python' },
              { title: '네트워크' },
              { title: 'Verilog HDL' },
              { title: 'Qt' },
              { title: '드론 개발' },
              { title: 'GUI' },
              { title: 'Raspberry Pi' },
              { title: 'C' },
            ],
          },
          {
            title: '자격증',
            items: [
              { title: '컴퓨터활용능력' },
              { title: '정보처리산업기사' },
              { title: 'PC정비사' },
              { title: '블록코딩' },
              { title: 'Python' },
              { title: '코딩 테스트' },
              { title: 'Entry' },
            ],
          },
        ],
      },
      {
        title: '보안 · 네트워크',
        items: [
          {
            title: '보안',
            items: [
              { title: '모의해킹' },
              { title: 'ISMS-P' },
              { title: 'Forensic' },
              { title: '시스템 해킹' },
              { title: '악성코드' },
              { title: '리버싱' },
            ],
          },
          {
            title: '네트워크',
            items: [
              { title: '네트워크' },
              { title: '프로토콜' },
              { title: 'IoT' },
              { title: '임베디드' },
              { title: 'Python' },
              { title: 'C#' },
              { title: '빅데이터' },
            ],
          },
          {
            title: '시스템',
            items: [
              { title: 'Linux' },
              { title: 'Shell Script' },
              { title: 'Powershell' },
              { title: '운영체제' },
              { title: 'Windows Server' },
              { title: '시스템 해킹' },
              { title: '도메인' },
              { title: 'Microsoft Windows' },
              { title: '동시성' },
              { title: '가상화' },
            ],
          },
          {
            title: '클라우드',
            items: [
              { title: 'AWS' },
              { title: 'Docker' },
              { title: 'Azure' },
              { title: 'Google Cloud Platform' },
              { title: 'Kubernetes' },
              { title: '서버리스' },
              { title: '네트워크' },
              { title: 'CI/CD' },
              { title: 'MSA' },
              { title: 'Terraform' },
              { title: 'SonarQube' },
              { title: 'Spring Cloud' },
            ],
          },
          {
            title: '블록체인',
            items: [
              { title: '블록체인' },
              { title: 'DApp' },
              { title: 'Ethereum' },
              { title: 'NFT' },
              { title: 'Solidity' },
              { title: 'Truffle' },
            ],
          },
          {
            title: '자격증',
            items: [
              { title: 'ISMS-P' },
              { title: '네트워크' },
              { title: 'Forensic' },
              { title: 'AWS' },
              { title: 'Azure' },
              { title: 'CCNA' },
            ],
          },
          {
            title: '기타',
            items: [
              { title: '네트워크' },
              { title: '임베디드' },
              { title: 'MS-Office' },
              { title: 'Python' },
              { title: '빅데이터' },
              { title: 'Cheat Engine' },
              { title: 'Frida' },
              { title: '정보처리기사' },
            ],
          },
        ],
      },
      {
        title: '데이터 사이언스',
        items: [
          {
            title: '데이터 분석',
            items: [
              { title: 'Python' },
              { title: 'Pandas' },
              { title: 'R' },
              { title: 'SQL' },
              { title: 'Excel' },
              { title: '빅데이터' },
              { title: '머신러닝' },
              { title: '웹 크롤링' },
              { title: 'Numpy' },
            ],
          },
          {
            title: '인공지능',
            items: [
              { title: '머신러닝' },
              { title: '딥러닝' },
              { title: 'Tensorflow' },
              { title: 'Keras' },
              { title: '컴퓨터 비전' },
              { title: '인공신경망' },
              { title: '강화학습' },
              { title: 'Kaggle' },
            ],
          },
          {
            title: '데이터 시각화',
            items: [
              { title: 'Pandas' },
              { title: 'R' },
              { title: 'Tableau' },
              { title: 'Matplotlib' },
              { title: 'Power BI' },
              { title: 'Seaborn' },
              { title: 'Numpy' },
            ],
          },
          {
            title: '데이터 수집 · 처리',
            items: [
              { title: '웹 크롤링' },
              { title: '데이터 엔지니어링' },
              { title: 'Kafka' },
              { title: 'Selenium' },
            ],
          },
          {
            title: '자격증',
            items: [
              { title: 'ADsP' },
              { title: 'Keras' },
              { title: '딥러닝' },
              { title: 'Alteryx' },
            ],
          },
          {
            title: '기타',
            items: [
              { title: '디지털 리터러시' },
              { title: '면접' },
              { title: 'OpenCV' },
              { title: 'Process Mining' },
              { title: 'RPA' },
              { title: '서비스 기획' },
              { title: '이력서' },
            ],
          },
        ],
      },
      {
        title: '게임 개발',
        items: [
          {
            title: '게임 프로그래밍',
            items: [{ title: 'Unity' }, { title: 'Roblox' }],
          },
          { title: '게임 기획', items: [{ title: '게임 기획' }] },
          {
            title: '게임 아트 · 그래픽',
            items: [
              { title: 'ZBrush' },
              { title: '3ds MAX' },
              { title: 'Blender' },
              { title: 'MAYA' },
              { title: '캐릭터 디자인' },
              { title: '애니메이션' },
            ],
          },
          { title: '기타' },
          { title: '청강대 게임스쿨' },
        ],
      },
      {
        title: '크리에이티브',
        items: [
          {
            title: 'CAD · 3D 모델링',
            items: [
              { title: 'CAD' },
              { title: 'MAYA' },
              { title: 'ZBrush' },
              { title: '3ds MAX' },
              { title: 'Blender' },
              { title: 'Catia' },
              { title: 'SOLIDWORKS' },
            ],
          },
          {
            title: '웹 퍼블리싱',
            items: [
              { title: 'HTML/CSS' },
              { title: '웹 디자인' },
              { title: 'jQeury' },
              { title: '반응형 앱' },
              { title: '인터랙티브 앱' },
              { title: 'JavaScript' },
              { title: 'Flex' },
              { title: '클론코딩' },
              { title: 'Sass' },
              { title: '포트폴리오' },
              { title: 'Three.js' },
              { title: 'SVG' },
            ],
          },
          {
            title: 'UX/UI',
            items: [
              { title: '모바일 디자인' },
              { title: '프로토타이핑' },
              { title: 'Figma' },
              { title: 'XD' },
              { title: '웹 디자인' },
              { title: 'Sketch' },
              { title: 'HTML/CSS' },
              { title: '서비스 기획' },
              { title: 'UX 리서치' },
              { title: 'iOS Autolayout' },
              { title: 'jQeury' },
              { title: 'ProtoPie' },
            ],
          },
          {
            title: '그래픽 디자인',
            items: [
              { title: 'Photoshop' },
              { title: '드로잉' },
              { title: '이모티콘' },
              { title: 'Illustrator' },
              { title: '캐릭터 디자인' },
              { title: 'CLIP STUDIO PAINT' },
              { title: 'InDesign' },
              { title: 'Animate' },
              { title: 'Figma' },
              { title: '콘텐츠 마케팅' },
              { title: 'CAD' },
              { title: 'CNC' },
            ],
          },
          {
            title: '디자인 툴',
            items: [
              { title: 'Photoshop' },
              { title: 'Figma' },
              { title: '프로토타이핑' },
              { title: 'MAYA' },
              { title: '모바일 디자인' },
              { title: 'Illustrator' },
              { title: 'XD' },
              { title: '웹 디자인' },
            ],
          },
          {
            title: '사진 · 영상',
            items: [
              { title: '영상제작' },
              { title: 'After Effects' },
              { title: '사진' },
              { title: 'Premiere Pro' },
              { title: '유튜브' },
              { title: '모션그래픽' },
              { title: 'Final Cut Pro' },
              { title: 'Davinci Resolve' },
              { title: 'Lightroom' },
              { title: 'Motion 5' },
              { title: 'VideoScribe' },
            ],
          },
          {
            title: '자격증',
            items: [
              { title: '웹 디자인' },
              { title: 'HTML/CSS' },
              { title: 'jQuery' },
            ],
          },
          {
            title: 'VR/AR',
            items: [
              { title: 'VR/AR' },
              { title: 'Unity' },
              { title: '메타버스' },
            ],
          },
          {
            title: '사운드',
            items: [
              { title: '작곡' },
              { title: '음향 시스템' },
              { title: 'Studio One' },
            ],
          },
          {
            title: '기타',
            items: [
              { title: 'Lua' },
              { title: 'EPUB' },
              { title: '플랫폼 비즈니스' },
              { title: '이모티콘' },
              { title: 'Sigil' },
            ],
          },
        ],
      },
      {
        title: '직무 · 마케팅',
        items: [
          {
            title: '오피스',
            items: [
              { title: '업무 생산성' },
              { title: '카피라이팅' },
              { title: '프로젝트 관리' },
            ],
          },
          {
            title: '마케팅',
            items: [
              { title: '디지털 마케팅' },
              { title: '퍼포먼스 마케팅' },
              { title: '콘텐츠 마케팅' },
              { title: '그로스해킹' },
              { title: 'Google Analytics' },
              { title: '마케팅 이론' },
              { title: '카페라이팅' },
              { title: '블로그' },
              { title: 'CRM 마케팅' },
            ],
          },
          {
            title: '기획 · 전략 · PM',
            items: [
              { title: '업무 생산성' },
              { title: '협업 툴' },
              { title: '서비스 기획' },
              { title: '프로젝트 관리' },
              { title: 'PT' },
              { title: '프로토타이핑' },
              { title: '경영노하우' },
              { title: 'Notion' },
              { title: 'PowerPoint' },
              { title: '카피라이팅' },
              { title: '게임기획' },
              { title: 'HR' },
            ],
          },
          {
            title: '업무 자동화',
            items: [
              { title: '웹 크롤링' },
              { title: 'Selenium' },
              { title: 'RPA' },
              { title: 'VBA' },
              { title: 'UiPath' },
              { title: 'Power Automate' },
            ],
          },
          {
            title: '금융',
            items: [
              { title: '투자' },
              { title: '퀀트' },
              { title: '차트분석' },
              { title: 'Pandas' },
              { title: '재테크' },
              { title: '챗봇' },
              { title: 'Anaconda' },
              { title: 'Plotly' },
              { title: '금융공학' },
            ],
          },
          {
            title: '경영',
            items: [
              { title: '경영노하우' },
              { title: '회계' },
              { title: '독서법' },
              { title: '재무' },
              { title: 'HR' },
              { title: '세무' },
              { title: '재테크' },
              { title: '마케팅 이론' },
              { title: '빅데이터' },
              { title: 'Visual Studio Code' },
              { title: 'CFO' },
              { title: '생산관리' },
            ],
          },
          {
            title: '자격증',
            items: [{ title: '컴퓨터활용능력' }, { title: 'Excel' }],
          },
          {
            title: '기타',
            items: [
              { title: '커뮤니케이션' },
              { title: '스피치' },
              { title: '데이터 엔지니어링' },
            ],
          },
        ],
      },
      {
        title: '학문 · 외국어',
        items: [
          {
            title: '수학',
            items: [
              { title: '통계' },
              { title: '미적분' },
              { title: '선형대수학' },
              { title: '게임수학' },
              { title: 'R' },
              { title: '딥러닝' },
              { title: '행렬' },
              { title: '머신러닝' },
              { title: 'DirectX' },
              { title: 'Excel' },
              { title: 'Scratch' },
              { title: '투자' },
            ],
          },
          {
            title: '외국어',
            items: [
              { title: '영어' },
              { title: 'OPIc' },
              { title: 'TOEIC' },
              { title: 'TOEIC Speaking' },
              { title: '중국어' },
              { title: 'SAT' },
              { title: '일본어' },
            ],
          },
          { title: '기타', items: [{ title: '경제학' }] },
        ],
      },
      {
        title: '커리어',
        items: [
          {
            title: '취업 · 이직',
            items: [
              { title: '면접' },
              { title: '포트폴리오' },
              { title: '기술면접' },
              { title: '이력서' },
            ],
          },
          {
            title: '개인 브랜딩',
            items: [
              { title: '집필' },
              { title: '스피치' },
              { title: '출간, 출판' },
              { title: 'PT' },
              { title: '콘텐츠 마케팅' },
              { title: '대인관계' },
              { title: '카피라이팅' },
              { title: 'PR' },
              { title: '경영노하우' },
              { title: '영상제작' },
            ],
          },
          {
            title: '창업',
            items: [
              { title: '스마트스토어' },
              { title: '디지털 마케팅' },
              { title: '경영노하우' },
              { title: '재무' },
            ],
          },
          {
            title: '기타',
            items: [{ title: '업무 생산성' }, { title: '블로그' }],
          },
        ],
      },
      {
        title: '교양',
        items: [
          {
            title: '교양',
            items: [
              { title: '투자' },
              { title: '재테크' },
              { title: '집필' },
              { title: '온라인 교육' },
              { title: '스피치' },
              { title: '영상제작' },
              { title: '사진' },
            ],
          },
        ],
      },
    ],
  },
  {
    title: '로드맵',
  },
  {
    title: '멘토링',
  },
  {
    title: '커뮤니티',
    items: [
      { title: '질문 & 답변' },
      { title: '자유주제' },
      { title: '스터디' },
      { title: '블로그' },
    ],
  },
  {
    title: '인프런',
    items: [
      { title: '수강평' },
      { title: '멘토링 후기' },
      { title: '공지사항' },
      { title: '인프런 스토리' },
      { title: '인프런 소개' },
      { title: '강의·기능 요청' },
    ],
  },
];
